name: Update AUR Package

on:
  release:
    types: [published]

jobs:
  update-aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release information
        id: release
        run: |
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "tarball_url=https://github.com/${{ github.repository }}/archive/${GITHUB_REF#refs/tags/}.tar.gz" >> $GITHUB_OUTPUT

      - name: Download and calculate SHA256
        id: checksum
        run: |
          wget -O release.tar.gz "${{ steps.release.outputs.tarball_url }}"
          echo "sha256=$(sha256sum release.tar.gz | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Setup SSH for AUR
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

      - name: Clone AUR repository
        run: |
          ssh-keyscan -H aur.archlinux.org >> ~/.ssh/known_hosts
          git clone ssh://aur@aur.archlinux.org/proton-game-saves.git aur-repo
          cd aur-repo
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Update PKGBUILD
        run: |
          cd aur-repo
          # Update version
          sed -i "s/^pkgver=.*/pkgver=${{ steps.release.outputs.version }}/" PKGBUILD
          # Update checksum
          sed -i "s/^sha256sums=.*/sha256sums=('${{ steps.checksum.outputs.sha256 }}')/" PKGBUILD
          # Reset pkgrel to 1 for new version
          sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD

      - name: Install makepkg dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts build-essential
          
          # Install pacman and makepkg for generating .SRCINFO
          wget https://github.com/Jguer/yay/releases/download/v12.0.5/yay_12.0.5_x86_64.tar.gz
          tar -xzf yay_12.0.5_x86_64.tar.gz
          sudo cp yay_12.0.5_x86_64/yay /usr/local/bin/
          
          # Alternative: use a container or install arch-install-scripts
          sudo apt-get install -y arch-install-scripts

      - name: Generate .SRCINFO
        run: |
          cd aur-repo
          # Use makepkg from arch-install-scripts to generate .SRCINFO
          makepkg --printsrcinfo > .SRCINFO

      - name: Commit and push to AUR
        run: |
          cd aur-repo
          git add PKGBUILD .SRCINFO
          git commit -m "Update to version ${{ steps.release.outputs.version }}

          - Automated update from GitHub release ${{ steps.release.outputs.tag_name }}
          - Updated pkgver to ${{ steps.release.outputs.version }}
          - Updated sha256sums
          - Reset pkgrel to 1"
          
          git push origin master

      - name: Create GitHub comment
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const release = context.payload.release;
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: release.number || release.id,
              body: `🎉 AUR package has been automatically updated to version \`${{ steps.release.outputs.version }}\`!\n\n` +
                    `📦 Install with: \`paru -S proton-game-saves\` or \`yay -S proton-game-saves\`\n\n` +
                    `🔗 [View on AUR](https://aur.archlinux.org/packages/proton-game-saves)`
            });
